<?php

namespace Database\Seeders;

use App\Models\Market;
use App\Models\Product;
use App\Models\ProductCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $iv = ProductCategory::where('slug', 'iv-fluids')->firstOrFail()->id;
        $ff = ProductCategory::where('slug', 'finished-formulations')->firstOrFail()->id;
        $md = ProductCategory::where('slug', 'medical-devices-and-disposables')->firstOrFail()->id;
        $rk = ProductCategory::where('slug', 'rapid-diagnostic-kits')->firstOrFail()->id;
        $vx = ProductCategory::where('slug', 'vaccines')->firstOrFail()->id;

        // Catalog data sourced from nymakpharma.com product tables.
        // [category, group, name, strength, pack_size]
        $catalog = [
            // IV Fluids
            [$iv, 'Antibacterial Infusions', 'Ciprofloxacin Intravenous Infusion', '200 mg / 100 ml', '100 ml'],
            [$iv, 'Antibacterial Infusions', 'Ofloxacin Intravenous Infusion', '200 mg / 100 ml', '100 ml'],
            [$iv, 'Antibacterial Infusions', 'Levofloxacin Intravenous Infusion', '500 mg / 100 ml', '100 ml'],
            [$iv, 'Antibacterial Infusions', 'Moxifloxacin Infusion', '400 mg / 100 ml', '100 ml'],
            [$iv, 'Antibacterial Infusions', 'Pefloxacin Infusion', '400 mg / 100 ml', '100 ml'],
            [$iv, 'Antifungal Infusions', 'Fluconazole Intravenous Infusion', '200 mg / 100 ml', '100 ml'],
            [$iv, 'Antiamoebic Infusions', 'Metronidazole Intravenous Infusion', '500 mg / 100 ml', '100 ml'],
            [$iv, 'Antiamoebic Infusions', 'Ornidazole Intravenous Infusion', '500 mg / 100 ml', '100 ml'],
            [$iv, 'Antiprotozoal Infusions', 'Tinidazole Intravenous Infusion', '800 mg / 400 ml', '400 ml'],
            [$iv, 'Analgesic & Antipyretic', 'Paracetamol Intravenous Infusion', '1000 mg / 100 ml', '100 ml'],
            [$iv, 'Fluid & Electrolyte Replenishers', 'Sodium Chloride Intravenous Infusion', '0.9% w/v', '100 ml, 500 ml & 1000 ml'],
            [$iv, 'Fluid & Electrolyte Replenishers', 'Sodium Chloride Intravenous Infusion', '0.45% w/v', '500 ml'],
            [$iv, 'Fluid & Electrolyte Replenishers', 'Ringer Lactate Intravenous Infusion', null, '500 ml & 1000 ml'],
            [$iv, 'Nutrient & Fluid Replenishers', 'Dextrose Intravenous Infusion', '5% w/v', '500 ml & 1000 ml'],
            [$iv, 'Nutrient & Fluid Replenishers', 'Dextrose Intravenous Infusion', '10% w/v', '500 ml & 1000 ml'],
            [$iv, 'Nutrient & Fluid Replenishers', 'Dextrose Intravenous Infusion', '25% w/v', '500 ml & 1000 ml'],
            [$iv, 'Nutrient & Fluid Replenishers', 'Sodium Chloride and Dextrose Intravenous Infusion', '0.9% w/v & 5% w/v', '500 ml & 1000 ml'],
            [$iv, 'Nutrient & Fluid Replenishers', 'Sodium Chloride and Dextrose Intravenous Infusion', '0.45% w/v & 5% w/v', '500 ml'],
            [$iv, 'Electrolyte & Dextrose IV Infusions', "Multiple Electrolytes 'P' & Dextrose Intravenous Infusion", null, '500 ml'],
            [$iv, 'Electrolyte & Dextrose IV Infusions', "Multiple Electrolytes 'G' & Dextrose Intravenous Infusion", null, '500 ml'],
            [$iv, 'Electrolyte & Dextrose IV Infusions', "Multiple Electrolytes 'M' & Dextrose Intravenous Infusion", null, '500 ml'],
            [$iv, 'Electrolyte & Dextrose IV Infusions', "Multiple Electrolytes 'E' & Dextrose Intravenous Infusion", null, '500 ml'],
            [$iv, 'Osmotic Diuretics', 'Mannitol Intravenous Infusion', '10% w/v', '100 ml & 500 ml'],
            [$iv, 'Osmotic Diuretics', 'Mannitol Intravenous Infusion', '20% w/v', '100 ml & 500 ml'],
            [$iv, 'Oxazolidinones', 'Linezolid Intravenous Infusion', '600 mg / 300 ml', '300 ml'],
            [$iv, 'Peritoneal Dialysis', 'Intraperitoneal Dialysis Fluid', '1.7% w/v', '1000 ml'],

            // Finished Formulations
            [$ff, 'Opioid Analgesics & Dependence Care', 'Buprenorphine Sublingual Tablets', '0.2 / 0.4 / 1 / 2 / 4 / 8 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Buprenorphine and Naloxone Tablets', '0.4 mg + 0.1 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Buprenorphine and Naloxone Tablets', '2 mg + 0.5 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Buprenorphine and Naloxone Tablets', '8 mg + 2 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Naltrexone Tablets', '50 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Methadone Hydrochloride Tablets', '5 / 10 / 20 mg', '10 Tablets'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Methadone Oral Concentrate', '5 mg/ml & 10 mg/ml', '100 ml'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Fentanyl Citrate Injection', '50 µg/ml', '2 ml Vial'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Buprenorphine Hydrochloride Injection', '0.3 mg/ml', '1 ml / 2 ml Ampoule'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Naloxone Hydrochloride Injection', '0.4 mg/ml', '1 ml Ampoule'],
            [$ff, 'Opioid Analgesics & Dependence Care', 'Nalbuphine Hydrochloride Injection', '10 mg / 20 mg', '1 ml Ampoule'],
            [$ff, 'Antimalarials', 'Chloroquine Phosphate Tablets', '100 mg / 250 mg', '10 Tablets'],
            [$ff, 'Antimalarials', 'Artemether and Lumefantrine Tablets', '20 mg + 120 mg', '6 Tablets'],
            [$ff, 'Antimalarials', 'Artemether and Lumefantrine Tablets', '40 mg + 240 mg', '6 Tablets'],
            [$ff, 'Antimalarials', 'Artemether and Lumefantrine Tablets', '80 mg + 480 mg', '6 Tablets'],
            [$ff, 'Antimalarials', 'Quinine Sulphate Tablets', '300 mg', '10 Tablets'],
            [$ff, 'Antimalarials', 'Primaquine Phosphate Tablets', '7.5 mg / 15 mg', '10 Tablets'],
            [$ff, 'Antimalarials', 'Sulfadoxine and Pyrimethamine Tablets', '500 mg + 25 mg', '10 Tablets'],
            [$ff, 'Antimalarials', 'Artesunate and Amodiaquine Tablets', '200 mg / 600 mg', '10 Tablets'],
            [$ff, 'Antimalarials', 'α-β Arteether Injection', '150 mg / 2 ml', '2 ml Ampoule'],
            [$ff, 'Antimalarials', 'Chloroquine Phosphate Injection', '40 mg/ml', '5 ml Ampoule / 30 ml Vial'],
            [$ff, 'Antimalarials', 'Sterile Quinine Dihydrochloride Concentrate', '300 mg/ml', '2 ml Ampoule'],
            [$ff, 'Antimalarials', 'Quinine Dihydrochloride Injection', '100 mg/ml', '1 ml Ampoule'],
            [$ff, 'Antimalarials', 'Artemether Injection', '40 mg/ml & 80 mg/ml', '1 ml Ampoule'],
            [$ff, 'Antimalarials', 'Chloroquine Phosphate Syrup', '80 mg / 5 ml', '60 ml'],
            [$ff, 'Supplemental Medication', 'Zinc Sulphate Dispersible Tablets', '20 mg', '10 Tablets'],
            [$ff, 'Supplemental Medication', 'Glucose Tablets', '3.4 gm', '10 Tablets'],
            [$ff, 'Supplemental Medication', 'Folic Acid Tablets', '5 mg', '10 Tablets'],
            [$ff, 'Supplemental Medication', 'Mecobalamin Tablets', '500 µg', '10 Tablets'],
            [$ff, 'Supplemental Medication', 'Mecobalamin Sublingual Tablets', '1500 µg', '10 Tablets'],
            [$ff, 'Supplemental Medication', 'Iron Sucrose Injection', '100 mg / 5 ml', '5 ml Ampoule'],
            [$ff, 'Supplemental Medication', 'Menaphthone Sodium Bisulphate Injection', '10 mg/ml', '1 ml Ampoule'],
            [$ff, 'Supplemental Medication', 'Vitamin B Complex Injection', null, '3 ml Ampoule'],
            [$ff, 'Supplemental Medication', 'Methylcobalamin Injection', '500 µg / 1000 µg', '1 ml / 2 ml Ampoule'],
            [$ff, 'Supplemental Medication', 'Magnesium Sulphate Injection', '50% w/v', '2 ml & 10 ml Ampoule'],
            [$ff, 'Supplemental Medication', 'Ferrous Sulphate + Folic Acid Syrup', '100 mg + 0.5 mg / 5 ml', '60 ml, 100 ml'],
            [$ff, 'Supplemental Medication', 'Multivitamin Mineral Syrup', null, '100 ml, 200 ml'],
            [$ff, 'Supplemental Medication', 'Sodium Feredetate Oral Solution', '231 mg / 5 ml (Syrup)', '100 ml'],
            [$ff, 'Supplemental Medication', 'Sodium Feredetate Oral Solution', '56 mg / ml (Drop)', '100 ml'],
            [$ff, 'Supplemental Medication', 'Multivitamin Mineral Lysine Drops', null, '30 ml'],
            [$ff, 'Supplemental Medication', 'Multiple Micronutrient Sachet', null, '1 g'],
            [$ff, 'Analgesics, Cough & Cold', 'Diclofenac Potassium Tablets', '50 mg', '10 Tablets'],
            [$ff, 'Analgesics, Cough & Cold', 'Cetirizine Di-hydrochloride Tablets', '10 mg', '10 Tablets'],
            [$ff, 'Analgesics, Cough & Cold', 'Salbutamol Tablets', '2 mg / 4 mg', '10 Tablets'],
            [$ff, 'Analgesics, Cough & Cold', 'Diclofenac Sodium Injection', '25 mg/ml', '3 ml Ampoule'],
            [$ff, 'Analgesics, Cough & Cold', 'Salbutamol Syrup', '2 mg / 5 ml', '100 ml'],
            [$ff, 'Analgesics, Cough & Cold', 'Loratadine Syrup', '1 mg/ml', '100 ml'],
            [$ff, 'Analgesics, Cough & Cold', 'Dextromethorphan, Phenylephrine & Chlorpheniramine Syrup', '10 mg + 5 mg + 2 mg', '100 ml'],
            [$ff, 'Antiulcerants', 'Esomeprazole Magnesium Trihydrate Tablets', '40 mg', '10 Tablets'],
            [$ff, 'Antiulcerants', 'Famotidine Tablets', '20 mg', '10 Tablets'],
            [$ff, 'Antiulcerants', 'Rabeprazole Sodium Tablets', '20 mg', '10 Tablets'],
            [$ff, 'Antiulcerants', 'Aluminium Hydroxide + Magnesium Trisilicate Tablets', '250 mg + 500 mg', '10 Tablets'],
            [$ff, 'Antiulcerants', 'Cimetidine Tablets', '200 mg / 400 mg', '10 Tablets'],
            [$ff, 'Antiulcerants', 'Enteric Coated Rabeprazole and Domperidone SR Capsules', '20 mg / 30 mg', '10 Capsules'],
            [$ff, 'Antiulcerants', 'Omeprazole Capsules', '20 mg', '10 Capsules'],
            [$ff, 'Antiulcerants', 'Domperidone and Omeprazole Capsules', '10 mg / 20 mg', '10 Capsules'],
            [$ff, 'Antiulcerants', 'Ranitidine Injection', '25 mg/ml', '2 ml Ampoule'],
            [$ff, 'Antiemetics', 'Metoclopramide Tablets', '10 mg', '10 Tablets'],
            [$ff, 'Antiemetics', 'Metoclopramide Hydrochloride Injection', '5 mg/ml', '2 ml Ampoule / 10 ml Vial'],
            [$ff, 'Antiemetics', 'Chlorpromazine Injection', '50 mg/ml', '2 ml Ampoule'],
            [$ff, 'Antiemetics', 'Promethazine Hydrochloride Injection', '25 mg/ml', '2 ml Ampoule'],
            [$ff, 'Cephalosporins', 'Cefuroxime Axetil Tablets', '125 mg / 250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cefadroxil Dispersible Tablets', '250 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cefadroxil Tablets', '500 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cefixime Dispersible Tablets', '50 mg / 100 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cefixime Tablets', '200 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cefpodoxime Proxetil Dispersible Tablets', '200 mg', '10 Tablets'],
            [$ff, 'Cephalosporins', 'Cephalexin Capsules', '250 mg / 500 mg', '10 Capsules'],
            [$ff, 'Cephalosporins', 'Cefazolin Sodium for Injection', '500 mg / 1000 mg', '15 ml Vial'],
            [$ff, 'Cephalosporins', 'Cefepime for Injection', '1 gm / 2 gm', '20 ml Vial'],
            [$ff, 'Cephalosporins', 'Cefoperazone Injection', '500 mg', '10 ml Vial'],
            [$ff, 'Cephalosporins', 'Cefotaxime Sodium for Injection', '250 mg / 500 mg / 1000 mg', '15 ml Vial'],
            [$ff, 'Cephalosporins', 'Ceftazidime for Injection', '500 mg / 1000 mg', '10 ml Vial'],
            [$ff, 'Cephalosporins', 'Ceftriaxone Injection', '500 mg / 1000 mg', '15 ml Vial'],
            [$ff, 'Cephalosporins', 'Ceftriaxone and Sulbactam for Injection', '1000 mg + 500 mg', '20 ml Vial'],
            [$ff, 'Cephalosporins', 'Cefoperazone and Sulbactam for Injection', '500 mg + 500 mg / 1 g + 1 g', '20 ml Vial'],
            [$ff, 'Cephalosporins', 'Cefuroxime Sodium for Injection', '250 mg / 750 mg / 1000 mg', '8 ml / 15 ml / 25 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin Tablets', '250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin Capsules', '250 mg / 500 mg', '10 Capsules'],
            [$ff, 'Antibiotics — β-Lactam', 'Ampicillin and Cloxacillin Capsules', '500 mg', '10 Capsules'],
            [$ff, 'Antibiotics — β-Lactam', 'Flucloxacillin Capsules', '250 mg / 500 mg', '10 Capsules'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin Sodium for Injection', '500 mg', '10 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin and Potassium Clavulanate for Injection', '500 mg + 100 mg', '20 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin and Potassium Clavulanate for Injection', '1000 mg + 200 mg', '20 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Cloxacillin Sodium for Injection', '500 mg', '7 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Ampicillin for Injection', '500 mg / 1 gm', '15 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Piperacillin & Tazobactam for Injection', '1.125 gm / 2.25 gm / 4.5 gm', '30 ml Vial'],
            [$ff, 'Antibiotics — β-Lactam', 'Amoxycillin and Cloxacillin for Oral Suspension', '125 mg / 5 ml', '100 ml'],
            [$ff, 'Macrolides', 'Azithromycin Tablets', '250 mg / 500 mg / 1 gm', '6 / 3 / 10 Tablets'],
            [$ff, 'Macrolides', 'Azithromycin Oral Suspension', '200 mg / 5 ml', '15 ml'],
            [$ff, 'Macrolides', 'Erythromycin Stearate Tablets', '250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Antibacterials', 'Lincomycin Hydrochloride Capsules', '500 mg', '10 Capsules'],
            [$ff, 'Antibacterials', 'Co-trimoxazole Tablets', '480 mg / 960 mg', '10 Tablets'],
            [$ff, 'Antibacterials', 'Doxycycline Capsules', '100 mg', '10 Capsules'],
            [$ff, 'Antibacterials', 'Tetracycline Capsules', '250 mg / 500 mg', '10 Capsules'],
            [$ff, 'Antibacterials', 'Metronidazole Tablets', '200 mg / 400 mg', '10 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Zidovudine + Lamivudine + Nevirapine Combipack', '300 mg + 150 mg + 200 mg', '1 + 1 + 1 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Zidovudine Tablets', '300 mg', '10 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine Tablets', '150 mg', '10 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Nevirapine Tablets', '200 mg', '60 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Acyclovir Tablets', '200 mg / 400 mg / 800 mg', '10 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lopinavir and Ritonavir Tablets', '200 mg / 50 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Raltegravir Tablets', '400 mg', '60 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Tenofovir, Lamivudine and Efavirenz Tablets', '300 mg + 300 mg + 600 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine and Zidovudine Tablets', '150 mg + 300 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine, Nevirapine and Stavudine Tablets', '150 mg + 200 mg + 30 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Stavudine and Lamivudine Tablets', '30 mg / 150 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine and Tenofovir Tablets', '300 mg + 300 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Darunavir Tablets', '600 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Nevirapine Dispersible Tablets', '50 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine, Nevirapine and Zidovudine Paediatric Tablets', '30 mg / 50 mg / 60 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Lamivudine and Zidovudine Dispersible Tablets', '30 mg + 60 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Ritonavir Tablets', '100 mg', '30 Tablets'],
            [$ff, 'Antiretrovirals (ARVs)', 'Atazanavir Capsules', '300 mg', '30 Capsules'],
            [$ff, 'Anaesthetics', 'Haloperidol Tablets', '5 mg', '10 Tablets'],
            [$ff, 'Anaesthetics', 'Bupivacaine Hydrochloride in Dextrose Injection', '5 mg/ml', '4 ml Ampoule'],
            [$ff, 'Anaesthetics', 'Haloperidol Injection', '5 mg/ml', '1 ml Ampoule'],
            [$ff, 'Anaesthetics', 'Lidocaine Injection', '2%', '2 ml Ampoule'],
            [$ff, 'Penems', 'Meropenem Injection', '500 mg / 1 gm', '30 ml Vial'],
            [$ff, 'Penems', 'Imipenem and Cilastatin for Injection', '250 mg + 250 mg / 500 mg + 500 mg', '20 ml Vial'],
            [$ff, 'Anti-Diabetics', 'Glibenclamide Tablets', '2.5 mg / 5 mg', '10 Tablets'],
            [$ff, 'Anti-Diabetics', 'Metformin Hydrochloride Tablets', '500 mg / 850 mg', '10 Tablets'],
            [$ff, 'Erectile Dysfunction', 'Sildenafil Citrate Tablets', '50 mg / 100 mg', '4 Tablets'],
            [$ff, 'Erectile Dysfunction', 'Tadalafil Tablets', '20 mg', '4 / 10 Tablets'],
            [$ff, 'Antibiotics — Quinolones', 'Ciprofloxacin Tablets', '250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Antibiotics — Quinolones', 'Ciprofloxacin + Tinidazole Tablets', '500 mg + 600 mg', '10 Tablets'],
            [$ff, 'Antibiotics — Quinolones', 'Norfloxacin Tablets', '400 mg', '10 Tablets'],
            [$ff, 'Antibiotics — Quinolones', 'Ofloxacin Tablets', '200 mg / 400 mg', '10 Tablets'],
            [$ff, 'Antibiotics — Quinolones', 'Levofloxacin Tablets', '250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Antidiarrhoeals', 'Loperamide Hydrochloride Tablets', '2 mg', '10 Tablets'],
            [$ff, 'Antidiarrhoeals', 'Oral Rehydration Salt (ORS)', null, '10.5 gm / 20.5 gm / 21 gm'],
            [$ff, 'Immunosuppressants', 'Sirolimus Tablets', '1 mg / 2 mg', '10 Tablets'],
            [$ff, 'Anticoagulants', 'Heparin Injection', '25000 IU/5 ml, 5000 IU/5 ml', '5 ml Vial'],
            [$ff, 'Ovulation Stimulants', 'Clomiphene Citrate Tablets', '50 mg', '10 Tablets'],
            [$ff, 'Antispasmodics', 'Hyoscine Butylbromide Tablets', '10 mg', '10 Tablets'],
            [$ff, 'Antispasmodics', 'Drotaverine Hydrochloride Tablets', '40 mg / 80 mg', '10 Tablets'],
            [$ff, 'Antispasmodics', 'Hyoscine Butylbromide Injection', '20 mg/ml', '1 ml Ampoule'],
            [$ff, 'Antifungals', 'Fluconazole Capsules', '50 mg / 150 mg / 200 mg', '10 Capsules'],
            [$ff, 'Antifungals', 'Ketoconazole Tablets', '200 mg', '10 Tablets'],
            [$ff, 'Anthelmintics', 'Albendazole Tablets', '400 mg', '1 / 10 Tablets'],
            [$ff, 'Anthelmintics', 'Mebendazole Tablets', '100 mg / 500 mg', '10 Tablets'],
            [$ff, 'Anthelmintics', 'Tinidazole Tablets', '500 mg', '10 Tablets'],
            [$ff, 'Anthelmintics', 'Diethylcarbamazine Citrate Tablets', '100 mg / 200 mg', '10 Tablets'],
            [$ff, 'Anthelmintics', 'Mebendazole Oral Suspension', '100 mg / 5 ml', '30 ml'],
            [$ff, 'Anthelmintics', 'Pyrantel Pamoate Oral Suspension', '250 mg / 5 ml', '15 ml'],
            [$ff, 'Anthelmintics', 'Albendazole Suspension', '200 mg / 5 ml', '10 ml'],
            [$ff, 'Cardiovascular', 'Amlodipine Besilate Tablets', '5 mg / 10 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Rosuvastatin Tablets', '10 mg / 20 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Nifedipine Extended-Release Tablets', '20 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Atenolol Tablets', '50 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Frusemide Tablets', '10 mg / 40 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Frusemide Injection', '10 mg', '2 ml Ampoule'],
            [$ff, 'Cardiovascular', 'Atorvastatin Tablets', '10 mg / 20 mg', '10 Tablets'],
            [$ff, 'Cardiovascular', 'Atropine Injection', '1 mg/ml', '1 ml Ampoule'],
            [$ff, 'Cardiovascular', 'Nitroglycerin Injection', '5 mg/ml', '5 ml Ampoule'],
            [$ff, 'Haemostatic Agents', 'Ethamsylate Tablets', '250 mg / 500 mg', '10 Tablets'],
            [$ff, 'Haemostatic Agents', 'Ethamsylate Injection', '250 mg / 2 ml', '2 ml Ampoule'],
            [$ff, 'Antiasthmatics', 'Aminophylline Injection', '25 mg/ml', '10 ml Ampoule'],
            [$ff, 'Anti-Inflammatories', 'Dexamethasone Sodium Phosphate Injection', '4 mg/ml', '2 ml Ampoule'],
            [$ff, 'Anxiolytics', 'Diazepam Tablets', '5 mg / 10 mg', '10 Tablets'],
            [$ff, 'Anxiolytics', 'Alprazolam Tablets', '0.25 mg / 0.5 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Amoxicillin & Potassium Clavulanate Tablets', '375 mg / 625 mg / 1000 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Amoxicillin & Potassium Clavulanate Dispersible Tablets', '228.2 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefixime & Potassium Clavulanate Tablets', '162.5 mg / 325 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefixime & Potassium Clavulanate Dispersible Tablets', '81.25 mg / 162.5 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefpodoxime & Potassium Clavulanate Tablets', '325 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefpodoxime & Potassium Clavulanate Dispersible Tablets', '162.51 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefadroxil & Potassium Clavulanate Tablets', '625 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Cefuroxime Axetil & Potassium Clavulanate Tablets', '312.5 mg', '10 Tablets'],
            [$ff, 'Clavulanate Combinations', 'Amoxycillin & Potassium Clavulanate Oral Suspension', '228.5 / 312.5 / 457 mg', '100 ml'],
            [$ff, 'Dry Powder Injections', 'Esomeprazole for Injection', '40 mg', '5 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Rabeprazole for Injection', '20 mg', '5 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Lansoprazole for Injection', '30 mg', '10 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Omeprazole for Injection', '40 mg', '10 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Pantoprazole for Injection', '40 mg', '10 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Artesunate for Injection', '30 / 60 / 120 / 150 / 180 / 210 / 240 mg', 'Vial'],
            [$ff, 'Dry Powder Injections', 'Teicoplanin for Injection', '200 mg / 400 mg', '10 ml / 20 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Vancomycin Hydrochloride for Injection', '500 mg / 1 g', '10 ml / 20 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Aciclovir for Injection', '250 mg / 500 mg', '10 ml / 20 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Clarithromycin for Injection', '500 mg', '15 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Daptomycin for Injection', '350 mg / 500 mg', '20 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Voriconazole for Injection', '200 mg', '15 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Anidulafungin for Injection', '100 mg', '30 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Azithromycin for Injection', '500 mg', '12 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Aztreonam for Injection', '500 mg / 1 g / 2 g', '15 ml Vial'],
            [$ff, 'Dry Powder Injections', 'Methylprednisolone for Injection', '500 mg / 1000 mg', '20 ml Vial'],

            // Medical Devices & Disposables
            [$md, 'Syringes & Needles', 'Insulin Syringe', null, null],
            [$md, 'Syringes & Needles', 'Single Use Syringe', null, null],
            [$md, 'Syringes & Needles', 'Single Use Needle', null, null],
            [$md, 'Syringes & Needles', 'Pen Needles', null, null],
            [$md, 'Syringes & Needles', 'Disposable Spinal Needle', null, null],
            [$md, 'Syringes & Needles', 'A.V. Fistula Needle', null, null],
            [$md, 'IV Access & Infusion', '3-Way Stop Cock', null, null],
            [$md, 'IV Access & Infusion', '3-Way Stop Cock with Extension Tube', null, null],
            [$md, 'IV Access & Infusion', 'Low / High Pressure Extension Tube', null, null],
            [$md, 'IV Access & Infusion', 'Extension Tube with T Connector', null, null],
            [$md, 'IV Access & Infusion', 'Extension Tube with Needle-Free Y Site', null, null],
            [$md, 'IV Access & Infusion', 'Flow Regulator with Extension Tube', null, null],
            [$md, 'IV Access & Infusion', 'Multi-Way Extension Tubes / Connectors', null, null],
            [$md, 'IV Access & Infusion', 'Safety I.V. Cannula / Catheter', null, null],
            [$md, 'IV Access & Infusion', 'I.V. Cannula with Wings & Injection Port', null, null],
            [$md, 'IV Access & Infusion', 'I.V. Cannula without Wings & Injection Port', null, null],
            [$md, 'IV Access & Infusion', 'I.V. Cannula with Suturable Wings & Snap Port Cap', null, null],
            [$md, 'IV Access & Infusion', 'Flash Back I.V. Cannula / Catheter', null, null],
            [$md, 'IV Access & Infusion', 'Infusion Set', null, null],
            [$md, 'IV Access & Infusion', 'Measured Volume Administration Set', null, null],
            [$md, 'IV Access & Infusion', 'Blood Administration Set', null, null],
            [$md, 'IV Access & Infusion', 'Scalp Vein Set', null, null],
            [$md, 'Patient Care & Urology', 'Foley Balloon Catheter', null, null],
            [$md, 'Patient Care & Urology', 'Urine Bag', null, null],
            [$md, 'Patient Care & Urology', 'Oxygen Mask', null, null],
            [$md, 'Patient Care & Urology', 'Surgical Mask', null, null],
            [$md, 'Surgical & Wound Care', 'Sutures (Vicryl)', null, null],
            [$md, 'Surgical & Wound Care', 'Surgical Gloves', null, null],
            [$md, 'Surgical & Wound Care', 'Examination Gloves', null, null],
            [$md, 'Surgical & Wound Care', 'Blood Collection Tube', null, null],
            [$md, 'Surgical & Wound Care', 'Absorbent Cotton Wool', '100 gm / 250 gm / 400 gm / 500 gm', null],
            [$md, 'Surgical & Wound Care', 'Absorbent Gauze Roll', null, null],
            [$md, 'Surgical & Wound Care', 'Absorbent Gauze Swab', null, null],
            [$md, 'Surgical & Wound Care', 'Adhesive Tape', '2.5 cm / 5 cm / 18 cm', null],
            [$md, 'Surgical & Wound Care', 'Crepe Bandage', null, null],
        ];

        foreach ($catalog as $i => [$category, $group, $name, $strength, $pack]) {
            Product::create([
                'product_category_id' => $category,
                'therapeutic_group' => $group,
                'name' => $name,
                'slug' => Str::slug($name.'-'.($strength ?? '').'-'.$i),
                'strength' => $strength,
                'pack_size' => $pack,
                'sort_order' => $i,
                'has_detail_page' => false,
            ]);
        }

        // Rapid diagnostic kits use the `specimen` column instead of strength/pack.
        $kits = [
            ['HIV 1 & 2 Test', 'Whole Blood / Serum / Plasma'],
            ['HIV-Ab / Ag 4th Gen Rapid Test', 'Whole Blood / Serum / Plasma'],
            ['HBsAg Card Test', 'Whole Blood / Serum / Plasma'],
            ['HCV Card Test', 'Whole Blood / Serum / Plasma'],
            ['Syphilis Card Test', 'Serum / Plasma'],
            ['Pregnancy Test', 'Urine'],
            ['LH (Ovulation) Test', 'Urine'],
            ['Malaria Pf / Pv Antigen Test', 'Whole Blood'],
            ['Malaria Pf / Pan Antigen Test', 'Whole Blood'],
            ['Typhoid IgG / IgM Test', 'Whole Blood / Serum / Plasma'],
            ['Chikungunya IgG / IgM Test', 'Whole Blood / Serum / Plasma'],
            ['Leptospira IgM & IgG Card', 'Whole Blood / Serum / Plasma'],
            ['H. Pylori Antibody Rapid Test Device', 'Whole Blood / Serum / Plasma'],
            ['Toxoplasma IgG / IgM Test', 'Whole Blood / Serum / Plasma'],
            ['Troponin I Test', 'Whole Blood / Serum / Plasma'],
            ['Scrub Typhus Test', 'Whole Blood / Serum / Plasma'],
            ['Leishmania Ab Test', 'Whole Blood / Serum / Plasma'],
            ['Urinalysis Strips', null],
            ['Dengue Diagnostic Solution', null],
            ['Urine Strip 10P Kit', 'Urine'],
        ];

        foreach ($kits as $i => [$name, $specimen]) {
            Product::create([
                'product_category_id' => $rk,
                'therapeutic_group' => 'Rapid Tests',
                'name' => $name,
                'slug' => Str::slug($name.'-kit-'.$i),
                'specimen' => $specimen,
                'sort_order' => $i,
            ]);
        }

        // Vaccines & antisera — description column carries the presentation detail.
        $vaccines = [
            ['Snake Venom Antiserum', 'Polyvalent Enzyme Refined Equine Immunoglobulins (Liquid)', '10 ml Vial'],
            ['Combipack of Snake Venom Antiserum with Sterile Water for Injection BP', 'Lyophilized, Polyvalent Enzyme Refined Equine Immunoglobulins', '10 ml Vial with 10 ml Ampoule'],
            ['Tetanus Antitoxin BP 1500 IU', 'Enzyme Refined Equine Immunoglobulins (Liquid)', '1 ml Vial'],
            ['Tetanus Antitoxin BP 1500 IU with Sterilized Water for Injection BP', 'Lyophilized, Enzyme Refined Equine Immunoglobulins', '1 ml Vial with 1 ml Ampoule'],
        ];

        foreach ($vaccines as $i => [$name, $desc, $pack]) {
            Product::create([
                'product_category_id' => $vx,
                'therapeutic_group' => 'Antisera & Immunoglobulins',
                'name' => $name,
                'slug' => Str::slug($name.'-'.$i),
                'description' => $desc,
                'pack_size' => $pack,
                'sort_order' => $i,
            ]);
        }

        $this->seedBrandedProducts($ff);
    }

    /**
     * Marketed brand products photographed for the Liberia and Sierra Leone
     * portfolios (Resources/Nymak Product Pictures). These get detail pages
     * because they carry real content; generic catalog rows do not.
     */
    private function seedBrandedProducts(int $ff): void
    {
        $liberia = Market::where('slug', 'liberia')->firstOrFail()->id;
        $sierraLeone = Market::where('slug', 'sierra-leone')->firstOrFail()->id;

        // [market, file slug, brand name, composition/therapeutic note]
        $products = [
            [$liberia, 'alumak-20-120-tab', 'Alumak 20/120 Tablets', 'Artemether 20 mg + Lumefantrine 120 mg antimalarial tablets.'],
            [$liberia, 'alumak-80-480-tab', 'Alumak 80/480 Tablets', 'Artemether 80 mg + Lumefantrine 480 mg antimalarial tablets.'],
            [$liberia, 'alumak-sp', 'Alumak SP', 'Artemether and Lumefantrine oral suspension for paediatric malaria treatment.'],
            [$liberia, 'alzolemak-tab', 'Alzolemak Tablets', 'Albendazole broad-spectrum anthelmintic tablets.'],
            [$liberia, 'apetimak', 'Apetimak', 'Appetite-stimulant formulation supplied under the Apetimak brand.'],
            [$liberia, 'athermak-inj', 'Athermak Injection', 'α-β Arteether antimalarial injection for severe malaria treatment.'],
            [$liberia, 'cefmak-inj', 'Cefmak Injection', 'Ceftriaxone broad-spectrum cephalosporin injection.'],
            [$liberia, 'cipromak-500-tab', 'Cipromak 500 Tablets', 'Ciprofloxacin 500 mg fluoroquinolone antibiotic tablets.'],
            [$liberia, 'clearmak-susp', 'Clearmak Suspension', 'Oral suspension supplied under the Clearmak brand.'],
            [$liberia, 'cloxamak-cap', 'Cloxamak Capsules', 'Cloxacillin penicillinase-resistant antibiotic capsules.'],
            [$liberia, 'cold-mak', 'Cold Mak', 'Cold and flu relief formulation supplied under the Cold Mak brand.'],
            [$liberia, 'cotrimak-susp', 'Cotrimak Suspension', 'Co-trimoxazole antibacterial oral suspension.'],
            [$liberia, 'doxymak-cap', 'Doxymak Capsules', 'Doxycycline 100 mg broad-spectrum antibiotic capsules.'],
            [$liberia, 'erythromak', 'Erythromak', 'Erythromycin macrolide antibiotic formulation.'],
            [$liberia, 'gas-relief-susp', 'Gas Relief Suspension', 'Antacid and anti-flatulent oral suspension.'],
            [$liberia, 'ibumak-susp', 'Ibumak Suspension', 'Ibuprofen oral suspension for pain, fever and inflammation.'],
            [$liberia, 'ketomak-tab', 'Ketomak Tablets', 'Ketoconazole 200 mg antifungal tablets.'],
            [$liberia, 'metromak-susp', 'Metromak Suspension', 'Metronidazole oral suspension for amoebic and anaerobic infections.'],
            [$liberia, 'metromak-tab', 'Metromak Tablets', 'Metronidazole tablets for amoebic and anaerobic infections.'],
            [$liberia, 'mzolemak-susp', 'Mzolemak Suspension', 'Anthelmintic oral suspension supplied under the Mzolemak brand.'],
            [$liberia, 'paramak-suspensions', 'Paramak Suspension', 'Paracetamol paediatric oral suspension for fever and pain relief.'],
            [$liberia, 'silmak-tab', 'Silmak Tablets', 'Tablet formulation supplied under the Silmak brand for the Liberian market.'],

            [$sierraLeone, 'alumak-dp', 'Alumak DP', 'Artemether and Lumefantrine dispersible antimalarial formulation.'],
            [$sierraLeone, 'alumak-forte', 'Alumak Forte', 'High-strength Artemether 80 mg + Lumefantrine 480 mg antimalarial tablets.'],
            [$sierraLeone, 'alumak-tab', 'Alumak Tablets', 'Artemether + Lumefantrine antimalarial tablets.'],
            [$sierraLeone, 'alzolemak-400-tab', 'Alzolemak 400 Tablets', 'Albendazole 400 mg broad-spectrum anthelmintic tablets.'],
            [$sierraLeone, 'amclomak-cap', 'Amclomak Capsules', 'Ampicillin and Cloxacillin combination antibiotic capsules.'],
            [$sierraLeone, 'amoximak-125-sp', 'Amoximak 125 Suspension', 'Amoxicillin 125 mg / 5 ml paediatric oral suspension.'],
            [$sierraLeone, 'amoximak-250-sp', 'Amoximak 250 Suspension', 'Amoxicillin 250 mg / 5 ml oral suspension.'],
            [$sierraLeone, 'amoximak-250-tab', 'Amoximak 250 Tablets', 'Amoxicillin 250 mg penicillin antibiotic tablets.'],
            [$sierraLeone, 'ampimak-250-cap', 'Ampimak 250 Capsules', 'Ampicillin 250 mg antibiotic capsules.'],
            [$sierraLeone, 'artemak-60-inj', 'Artemak 60 Injection', 'Artesunate 60 mg injection for severe malaria treatment.'],
            [$sierraLeone, 'biomak-syrup', 'Biomak Syrup', 'Nutritional syrup formulation supplied under the Biomak brand.'],
            [$sierraLeone, 'cefisimak-400-tab', 'Cefisimak 400 Tablets', 'Cefixime 400 mg third-generation cephalosporin tablets.'],
            [$sierraLeone, 'cefmak-inj', 'Cefmak Injection', 'Ceftriaxone broad-spectrum cephalosporin injection.'],
            [$sierraLeone, 'cipromak-500-tab', 'Cipromak 500 Tablets', 'Ciprofloxacin 500 mg fluoroquinolone antibiotic tablets.'],
            [$sierraLeone, 'clavmak-12', 'Clavmak 1.2 g Injection', 'Amoxicillin 1 g + Potassium Clavulanate 200 mg injection.'],
            [$sierraLeone, 'clavmak-228', 'Clavmak 228 Suspension', 'Amoxicillin and Potassium Clavulanate 228.5 mg oral suspension.'],
            [$sierraLeone, 'corcef-inj', 'Corcef Injection', 'Injectable cephalosporin antibiotic supplied under the Corcef brand.'],
            [$sierraLeone, 'cypmak-tab', 'Cypmak Tablets', 'Cyproheptadine tablets supplied under the Cypmak brand.'],
            [$sierraLeone, 'doxymak-cap', 'Doxymak Capsules', 'Doxycycline 100 mg broad-spectrum antibiotic capsules.'],
            [$sierraLeone, 'i-paramak-susp', 'I-Paramak Suspension', 'Ibuprofen and Paracetamol combination oral suspension.'],
            [$sierraLeone, 'ibumak-400-tab', 'Ibumak 400 Tablets', 'Ibuprofen 400 mg tablets for pain, fever and inflammation.'],
            [$sierraLeone, 'omemak-inj', 'Omemak Injection', 'Omeprazole 40 mg injection for acid-related disorders.'],
            [$sierraLeone, 'silmak-100-tab', 'Silmak 100 Tablets', 'Tablet formulation supplied under the Silmak brand for Sierra Leone.'],
            [$sierraLeone, 'zincomak-syrup', 'Zincomak Syrup', 'Zinc supplement syrup for paediatric nutrition and diarrhoea support.'],
        ];

        $marketFolder = [
            $liberia => 'liberia',
            $sierraLeone => 'sierra-leone',
        ];
        $marketSlug = [
            $liberia => 'liberia',
            $sierraLeone => 'sierra-leone',
        ];

        foreach ($products as $i => [$marketId, $file, $name, $note]) {
            Product::create([
                'product_category_id' => $ff,
                'market_id' => $marketId,
                'therapeutic_group' => 'Nymak Branded Range',
                'name' => $name,
                // '/' → '-' before slugging so "20/120" becomes "20-120", not "20120"
                'slug' => Str::slug(str_replace('/', '-', $name).'-'.$marketSlug[$marketId]),
                'description' => $note.' Manufactured under WHO-GMP conditions and supplied as part of the Nymak Pharma branded portfolio.',
                'image' => 'images/products/'.$marketFolder[$marketId].'/'.$file.'.webp',
                'has_detail_page' => true,
                'sort_order' => 500 + $i,
            ]);
        }
    }
}
